### ISSUE TITLE
gms::codeCheck() stuck in set definitions?

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/gms#8] opened 2021-12-02 15:15 UTC
Output for `remind/develop` as of [871873ae](https://github.com/remindmodel/remind/tree/871873aeb8a27ee621bb26f6a01f172968289484)
```
> gms::codeCheck() -> foo

 Running codeCheck...
 Finished data collection...            (time elapsed:   1.35)
 Naming conventions check done...       (time elapsed:   1.36)
  Running checkAppearance...
  Start variable matching...            (time elapsed:   0.06)
  Finished variable matching...         (time elapsed:  54.89)
 Investigated variable appearances...   (time elapsed:  56.27)
 Appearance check done...               (time elapsed:  56.33)
 Switch Appearance check done...        (time elapsed:  56.71)
 Interface collection and check done... (time elapsed:  56.78)
 Input folder check done...             (time elapsed:  56.78)
 Description check done...              (time elapsed:  56.78)
 All codeCheck tests passed!
There were 12 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: techpol.NDC: "sum" does not follow the given naming convetions (description = "$(sameas(tebiochp) OR sameas(te"bioigcc") OR sameas(te"bioigccc")) vm_cap(tregiterlf))")!
2: techpol.NDC: "*" does not follow the given naming convetions (description = "1000 =g= p40_ElecBioBound(tregi)  ")!
3: techpol.NDC: "sum" does not follow the given naming convetions (description = " vm_cap(tregite1)) ")!
4: techpol.NDC: "=g=" does not follow the given naming convetions (description = "p40_TechBound(tregiwind)*0.001")!
5: techpol.NDCplus: "sum" does not follow the given naming convetions (description = "$(sameas(tebiochp) OR sameas(te"bioigcc") OR sameas(te"bioigccc")) vm_cap(tregiterlf))")!
6: techpol.NDCplus: "*" does not follow the given naming convetions (description = "1000 =g= p40_ElecBioBound(tregi)  ")!
7: techpol.NDCplus: "sum" does not follow the given naming convetions (description = " vm_cap(tregite1)) ")!
8: techpol.NDCplus: "=g=" does not follow the given naming convetions (description = "p40_TechBound(tregiwind)*0.001")!
9: techpol.NPi2018: "sum" does not follow the given naming convetions (description = "$(sameas(tebiochp) OR sameas(te"bioigcc") OR sameas(te"bioigccc")) vm_cap(tregiterlf))")!
10: techpol.NPi2018: "*" does not follow the given naming convetions (description = "1000 =g= p40_ElecBioBound(tregi)  ")!
11: techpol.NPi2018: "sum" does not follow the given naming convetions (description = " vm_cap(tregite1)) ")!
12: techpol.NPi2018: "=g=" does not follow the given naming convetions (description = "p40_TechBound(tregiwind)*0.001")!
```
Code in question (at least the [first bit](https://github.com/remindmodel/remind/blob/871873aeb8a27ee621bb26f6a01f172968289484/modules/40_techpol/NDC/equations.gms#L9-L12)):
```
q40_ElecBioBound(t,regi)$(t.val gt 2015 AND (NOT cm_bioprod_histlim ge 0))..
***am minimum targets for certain technologies
    sum(te2rlf(te,rlf)$(sameas(te,"biochp") OR sameas(te,"bioigcc") OR sameas(te,"bioigccc")), vm_cap(t,regi,te,rlf))
      * 1000 =g= p40_ElecBioBound(t,regi);	 
```

Makes using `codeCheck()` kind of pointless if `remind/develop` doesn't pass either …

**Comment by giannou** [comment] 2021-12-03 11:49
the problem is related to this issue: https://github.com/remindmodel/remind/issues/594

**Comment by orichters** [comment] 2022-01-14 13:22
The actual error was meanwhile fixed in remind.

**Closed by orichters** 2022-01-14 13:22 UTC
Labels: bug
